name       : cmark
version    : 0.28.3
release    : 1
source     :
    - https://github.com/commonmark/cmark/archive/0.28.3.tar.gz : acc98685d3c1b515ff787ac7c994188dadaf28a2d700c10c1221da4199bae1fc
license    :
    - BSD-2-Clause
    - MIT
component  : programming
summary    : CommonMark parsing and rendering library and program in C
description: |
    cmark is the C reference implementation of CommonMark, a rationalized
    version of Markdown.
    
    It provides a shared library (libcmark) with functions for parsing
    CommonMark documents to an abstract syntax tree (AST), manipulating the
    AST, and rendering the document to HTML, groff man, LaTeX, CommonMark, or
    an XML representation of the AST. It also provides a command-line program
    (cmark) for parsing and rendering CommonMark documents.
setup      : |
    mkdir build && cd build
    %cmake .. \
        -DLIB_SUFFIX=64 \
        -DCMARK_STATIC=OFF
build      : |
    %make -C build
install    : |
    %make_install -C build
check      : |
    %make test -C build
