name       : cmark
version    : 0.29.0
release    : 2
source     :
    - https://github.com/commonmark/cmark/archive/0.29.0.tar.gz : 2558ace3cbeff85610de3bda32858f722b359acdadf0c4691851865bb84924a6
license    :
    - BSD-2-Clause
    - MIT
component  : programming.library
summary    : CommonMark parsing and rendering library and program in C
description: |
    cmark is the C reference implementation of CommonMark, a rationalized version of Markdown.

    It provides a shared library (libcmark) with functions for parsing CommonMark documents to an abstract syntax tree (AST), manipulating the AST, and rendering the document to HTML, groff man, LaTeX, CommonMark, or an XML representation of the AST. It also provides a command-line program (cmark) for parsing and rendering CommonMark documents.
setup      : |
    %cmake_ninja -DLIB_SUFFIX=64 -DCMARK_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
